version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - echo Installing app dependencies...
      - curl -o kubectl https://amazon-eks.s3.us-west-2.amazonaws.com/1.18.9/2020-11-02/bin/linux/amd64/kubectl   
      - chmod +x ./kubectl
      - mkdir -p $HOME/bin && cp ./kubectl $HOME/bin/kubectl && export PATH=$PATH:$HOME/bin
      - echo 'export PATH=$PATH:$HOME/bin' >> ~/.bashrc
      - source ~/.bashrc
      - echo 'Check kubectl version'
      - kubectl version --short --client
      - echo Starting sample app build process
  pre_build:
    commands:
      - echo check config 
      - echo check kubectl access
      - echo Logging in to Amazon ECR...
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - echo "implementing the image version in deployment.yaml"
      
  build:
    commands:
      - echo Building the Docker image.
      - version_line=$(grep  update.txt)
      - echo "current_version:$version_line"

# Set IFS to split the version into major, minor, and patch
      - IFS=':. ' read -r major minor patch <<< "$version_line"

# Increment the patch version
      - patch=${patch%%.*} 
      - patch=$((patch + 1))

# Write the new version back to version.txt
      - echo "version:$major.$minor.$patch" > update.txt

# Optionally, output the new version
      - echo "Updated Version:$major.$minor.$patch"