version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - echo Installing app dependencies...
      - curl -o kubectl https://amazon-eks.s3.us-west-2.amazonaws.com/1.18.9/2020-11-02/bin/linux/amd64/kubectl   
      - chmod +x ./kubectl
      - mkdir -p $HOME/bin && cp ./kubectl $HOME/bin/kubectl && export PATH=$PATH:$HOME/bin
      - echo 'export PATH=$PATH:$HOME/bin' >> ~/.bashrc
      - source ~/.bashrc
      - echo 'Check kubectl version'
      - kubectl version --short --client
      - echo Starting sample app build process
  pre_build:
    commands:
      - echo check config 
      - echo check kubectl access
      - echo Logging in to Amazon ECR...
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - echo "implementing the image version in deployment.yaml"
      
  build:
    commands:
      - echo Building the Docker image.
      - echo "implementing the image version in script "
      - CURRENT_VERSION="1.0.0" 
      - echo "current_version:$CURRENT_VERSION"
      - IFS= '.' read -a VERSION_PART <<< "$CURRENT_VERSION"
      - echo "Major:${VERSION_PART[0]}"
      - echo "Minor:${VERSION_PART[1]}"
      - echo "PAtch:${VERSION_PART[2]}"
      - VERSION_PART[2]= ((${VERSION_PART[2]} + 1))

      
  post_build:
    commands:
      - echo "deploying the application"
     
      - kubectl   apply -f deployment.yaml
